name: Build mkdocs

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  release:
    types: [ created ]  

env:
  SITE_BRANCH: ${{ 'gh-pages-ver' }}

jobs:
  build:

    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all commits/branches      

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install package
        run: |
          pip install mkdocs-material
          pip install git+git://github.com/jimporter/mike.git#egg=mike --upgrade

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "bot@jerbly.net"

      - name: Build the docs locally only
        if: github.event_name == 'pull_request'
        run:  |
          mike deploy dev -b ${{ env.SITE_BRANCH }} 

      - name: Deploy docs (if pushing to master)
        if: github.repository == 'jerbly/doctest' && github.event_name == 'push'
        run: |
          mike deploy dev -b ${{ env.SITE_BRANCH }} -p     

      - name: Get latest release tag
        if: github.event_name == 'release'
        id: latest
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          excludes: prerelease
          repository: ${{ github.repository }}

      - name: Release docs
        if: github.event_name == 'release'
        run: |
          echo Deploy as ${{ steps.latest.outputs.release }} 
          mike deploy -b ${{ env.SITE_BRANCH }} ${{ steps.latest.outputs.release }} -p
          mike set-default -b ${{ env.SITE_BRANCH }} ${{ steps.latest.outputs.release }} -p     
