name: Build mkdocs

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  release:
    types: [ created ]  

env:
  SITE_BRANCH: ${{ 'gh-pages-ver' }}

jobs:
  build:

    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all commits/branches      

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install package
        run: |
          pip install mkdocs-material==7.0.6 mike==0.5.5

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "bot@jerbly.net"

      - name: Build the docs locally only
        if: github.event_name == 'pull_request'
        run:  |
          mike deploy dev -b ${{ env.SITE_BRANCH }} 

      - name: Deploy docs (if pushing to master)
        id: deploy_dev
        if: github.repository == 'jerbly/doctest' && github.event_name == 'push'
        run: |
          mike deploy dev -b ${{ env.SITE_BRANCH }} -p
          echo '::set-output name=MIKE_VERSIONS::'$(mike list -b ${{ env.SITE_BRANCH }} | wc -l)     

      - name: Set dev as default
        if: steps.deploy_dev.outputs.MIKE_VERSIONS == 1
        run: |
          mike set-default dev -b ${{ env.SITE_BRANCH }} -p

      - name: Get latest release tag
        if: github.event_name == 'release' && !github.event.release.prerelease
        id: latest
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          excludes: prerelease
          repository: ${{ github.repository }}

      - name: Release docs
        if: github.event_name == 'release' && !github.event.release.prerelease
        run: |
          ls -l
          echo Deploy as ${{ steps.latest.outputs.release }} 
          mike deploy ${{ steps.latest.outputs.release }} -b ${{ env.SITE_BRANCH }} -p
          mike set-default ${{ steps.latest.outputs.release }} -b ${{ env.SITE_BRANCH }} -p     
