name: Build mkdocs

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all commits/branches      

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install package
        run: |
          pip install mkdocs-material
          pip install git+git://github.com/jimporter/mike.git#egg=mike --upgrade

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "bot@jerbly.net"

      # - name: Build the docs
      #   run:  |
      #     mike deploy 0.2

      - name: get latest release tag
        id: latest
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          excludes: prerelease
          repository: airctic/icevision

      - name: get latest pre-release tag
        id: prerelease
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: airctic/icevision          

      - name: Deploy docs (if pushing to master)
        if: github.repository == 'jerbly/doctest' && github.event_name == 'push'
        run: |
          echo Latest ${{ steps.latest.outputs.release }} Pre ${{ steps.prerelease.outputs.release }} 
          mike deploy dev -p
          mike set-default 0.2 -p
          