name: Release mkdocs

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all commits/branches      

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install package
        run: |
          pip install mkdocs-material
          pip install git+git://github.com/jimporter/mike.git#egg=mike --upgrade

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "bot@jerbly.net"

      - name: get latest release tag
        id: latest
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          excludes: prerelease
          repository: ${{ github.repository }}

      - name: Deploy docs
        run: |
          echo Deploy as ${{ steps.latest.outputs.release }} 
          mike deploy ${{ steps.latest.outputs.release }} -p
          mike set-default ${{ steps.latest.outputs.release }} -p
          